export declare const REQUESTED_TO_IANA_FOR_PATHWAYS: {
    'application/vnd.biopax.rdf+xml': string;
    'application/biopax.rdf+xml': string;
    'application/biopax+xml': string;
    'application/rdf+xml': string;
    'biopax': string;
    'application/owl+xml': string;
    'owl': string;
    'application/vnd.gpml+xml': string;
    'application/gpml+xml': string;
    'gpml': string;
    'xml': string;
    'application/xml': string;
    'application/ld+json': string;
    'application/json': string;
    'json': string;
    'jsonld': string;
    'pvjson': string;
    'application/pdf': string;
    'pdf': string;
    'image/png': string;
    'png': string;
    'image/svg+xml': string;
    'application/svg+xml': string;
    'svg': string;
    'text/genelist': string;
    'text/plain': string;
    'genelist': string;
    'text/pwf': string;
    'text/eugene': string;
    'eugene': string;
    'pwf': string;
};
export declare const SUPPORTED: string[];
export declare const IANA_TO_WP_API_BODY: {
    'application/vnd.biopax.rdf+xml': string;
    'application/vnd.gpml+xml': string;
    'application/ld+json': string;
    'application/pdf': string;
    'image/png': string;
    'image/svg+xml': string;
    'text/genelist': string;
    'text/pwf': string;
};
export declare const IANA_TO_WP_API_ENVELOPE: {
    'application/vnd.biopax.rdf+xml': string;
    'application/xml': string;
    'application/vnd.gpml+xml': string;
    'application/ld+json': string;
    'text/genelist': string;
    'text/pwf': string;
};
